interface_branding: owendots / Slackware-current
interface_branding_colour: {{accent:hex}}
interface_help_colour: {{muted:hex}}
interface_help_colour_bright: {{foreground:hex}}
term_font_scale: 2x2
term_margin: 32
term_margin_gradient: 0
term_background: ff{{background:hex}}
term_foreground: {{foreground:hex}}
term_background_bright: {{surface:hex}}
term_foreground_bright: {{bright_white:hex}}
term_palette: {{black:hex}};{{red:hex}};{{green:hex}};{{yellow:hex}};{{blue:hex}};{{magenta:hex}};{{cyan:hex}};{{white:hex}}
term_palette_bright: {{bright_black:hex}};{{bright_red:hex}};{{bright_green:hex}};{{bright_yellow:hex}};{{bright_blue:hex}};{{bright_magenta:hex}};{{bright_cyan:hex}};{{bright_white:hex}}
