vo=gpu-next
gpu-api=auto
hwdec=auto-safe
ao=pipewire
osd-font=JetBrainsMono Nerd Font Mono
osd-color='{{foreground}}'
osd-outline-color='{{background}}'
osd-shadow-offset=0
background-color='{{background}}'
save-position-on-quit=yes
